version: '2'

services:

  influxdb:
    env_file:
      - ./configuration.env
    build:
      context: ./docker/influxdb
      dockerfile: Dockerfile
    ports:
      - '8086:8086'
      - '8083:8083'
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    env_file:
      - ./configuration.env
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - config=/etc/grafana/grafana.ini

volumes:
  influxdb_data: {}
  grafana_data: {}